select * from category
insert into category values(1, '전국전체전체');

insert into category values(2, '전국전체교육');

insert into category values(3, '전국전체창업');

insert into category values(4, '전국전체주거');

insert into category values(5, '전국전체건강');
insert into category values(6, '전국전체기타');
insert into category values(7, '전국대학생전체');
insert into category values(8, '전국대학생교육');
insert into category values(9, '전국대학생창업');
insert into category values(10, '전국대학생주거');
insert into category values(11, '전국대학생건강');
insert into category values(12, '전국대학생기타');
insert into category values(13, '전국군인전체');
insert into category values(14, '전국군인교육');
insert into category values(15, '전국군인창업');
insert into category values(16, '전국군인주거');
insert into category values(17, '전국군인건강');
insert into category values(18, '전국군인기타');
insert into category values(19, '전국구직전체');
insert into category values(20, '전국구직교육');
insert into category values(21, '전국구직창업');
insert into category values(22, '전국구직주거');
insert into category values(23, '전국구직건강');
insert into category values(24, '전국구직기타');
insert into category values(25, '전국재직자전체');
insert into category values(26, '전국재직자교육');
insert into category values(27, '전국재직자창업');
insert into category values(28, '전국재직자주거');
insert into category values(29, '전국재직자건강');
insert into category values(30, '전국재직자기타');
insert into category values(31, '전국창업자전체');
insert into category values(32, '전국창업자교육');
insert into category values(33, '전국창업자창업');
insert into category values(34, '전국창업자주거');
insert into category values(35, '전국창업자건강');
insert into category values(36, '전국창업자기타');
insert into category values(37, '전국장애인전체');
insert into category values(38, '전국장애인교육');
insert into category values(39, '전국장애인창업');
insert into category values(40, '전국장애인주거');
insert into category values(41, '전국장애인건강');
insert into category values(42, '전국장애인기타');
insert into category values(43, '전국임신부전체');
insert into category values(44, '전국임신부교육');
insert into category values(45, '전국임신부창업');
insert into category values(46, '전국임신부주거');
insert into category values(47, '전국임신부건강');
insert into category values(48, '전국임신부기타');
insert into category values(49, '광주전체전체');
insert into category values(50, '광주전체교육');
insert into category values(51, '광주전체창업');
insert into category values(52, '광주전체주거');
insert into category values(53, '광주전체건강');
insert into category values(54, '광주전체기타');
insert into category values(55, '광주대학생전체');
insert into category values(56, '광주대학생교육');
insert into category values(57, '광주대학생창업');
insert into category values(58, '광주대학생주거');
insert into category values(59, '광주대학생건강');
insert into category values(60, '광주대학생기타');
insert into category values(61, '광주군인전체');
insert into category values(62, '광주군인교육');
insert into category values(63, '광주군인창업');
insert into category values(64, '광주군인주거');
insert into category values(65, '광주군인건강');
insert into category values(66, '광주군인기타');
insert into category values(67, '광주구직전체');
insert into category values(68, '광주구직교육');
insert into category values(69, '광주구직창업');
insert into category values(70, '광주구직주거');
insert into category values(71, '광주구직건강');
insert into category values(72, '광주구직기타');
insert into category values(73, '광주재직자전체');
insert into category values(74, '광주재직자교육');
insert into category values(75, '광주재직자창업');
insert into category values(76, '광주재직자주거');
insert into category values(77, '광주재직자건강');
insert into category values(78, '광주재직자기타');
insert into category values(79, '광주창업자전체');
insert into category values(80, '광주창업자교육');
insert into category values(81, '광주창업자창업');
insert into category values(82, '광주창업자주거');
insert into category values(83, '광주창업자건강');
insert into category values(84, '광주창업자기타');
insert into category values(85, '광주장애인전체');
insert into category values(86, '광주장애인교육');
insert into category values(87, '광주장애인창업');
insert into category values(88, '광주장애인주거');
insert into category values(89, '광주장애인건강');
insert into category values(90, '광주장애인기타');
insert into category values(91, '광주임신부전체');
insert into category values(92, '광주임신부교육');
insert into category values(93, '광주임신부창업');
insert into category values(94, '광주임신부주거');
insert into category values(95, '광주임신부건강');
insert into category values(96, '광주임신부기타');
insert into category values(97, '광주북구전체전체');
insert into category values(98, '광주북구전체교육');
insert into category values(99, '광주북구전체창업');
insert into category values(100, '광주북구전체주거');
insert into category values(101, '광주북구전체건강');
insert into category values(102, '광주북구전체기타');
insert into category values(103, '광주북구대학생전체');
insert into category values(104, '광주북구대학생교육');
insert into category values(105, '광주북구대학생창업');
insert into category values(106, '광주북구대학생주거');
insert into category values(107, '광주북구대학생건강');
insert into category values(108, '광주북구대학생기타');
insert into category values(109, '광주북구군인전체');
insert into category values(110, '광주북구군인교육');
insert into category values(111, '광주북구군인창업');
insert into category values(112, '광주북구군인주거');
insert into category values(113, '광주북구군인건강');
insert into category values(114, '광주북구군인기타');
insert into category values(115, '광주북구구직전체');
insert into category values(116, '광주북구구직교육');
insert into category values(117, '광주북구구직창업');
insert into category values(118, '광주북구구직주거');
insert into category values(119, '광주북구구직건강');
insert into category values(120, '광주북구구직기타');
insert into category values(121, '광주북구재직자전체');
insert into category values(122, '광주북구재직자교육');
insert into category values(123, '광주북구재직자창업');
insert into category values(124, '광주북구재직자주거');
insert into category values(125, '광주북구재직자건강');
insert into category values(126, '광주북구재직자기타');
insert into category values(127, '광주북구창업자전체');
insert into category values(128, '광주북구창업자교육');
insert into category values(129, '광주북구창업자창업');
insert into category values(130, '광주북구창업자주거');
insert into category values(131, '광주북구창업자건강');
insert into category values(132, '광주북구창업자기타');
insert into category values(133, '광주북구장애인전체');
insert into category values(134, '광주북구장애인교육');
insert into category values(135, '광주북구장애인창업');
insert into category values(136, '광주북구장애인주거');
insert into category values(137, '광주북구장애인건강');
insert into category values(138, '광주북구장애인기타');
insert into category values(139, '광주북구임신부전체');
insert into category values(140, '광주북구임신부교육');
insert into category values(141, '광주북구임신부창업');
insert into category values(142, '광주북구임신부주거');
insert into category values(143, '광주북구임신부건강');
insert into category values(144, '광주북구임신부기타');
insert into category values(145, '광주남구전체전체');
insert into category values(146, '광주남구전체교육');
insert into category values(147, '광주남구전체창업');
insert into category values(148, '광주남구전체주거');
insert into category values(149, '광주남구전체건강');
insert into category values(150, '광주남구전체기타');
insert into category values(151, '광주남구대학생전체');
insert into category values(152, '광주남구대학생교육');
insert into category values(153, '광주남구대학생창업');
insert into category values(154, '광주남구대학생주거');
insert into category values(155, '광주남구대학생건강');
insert into category values(156, '광주남구대학생기타');
insert into category values(157, '광주남구군인전체');
insert into category values(158, '광주남구군인교육');
insert into category values(159, '광주남구군인창업');
insert into category values(160, '광주남구군인주거');
insert into category values(161, '광주남구군인건강');
insert into category values(162, '광주남구군인기타');
insert into category values(163, '광주남구구직전체');
insert into category values(164, '광주남구구직교육');
insert into category values(165, '광주남구구직창업');
insert into category values(166, '광주남구구직주거');
insert into category values(167, '광주남구구직건강');
insert into category values(168, '광주남구구직기타');
insert into category values(169, '광주남구재직자전체');
insert into category values(170, '광주남구재직자교육');
insert into category values(171, '광주남구재직자창업');
insert into category values(172, '광주남구재직자주거');
insert into category values(173, '광주남구재직자건강');
insert into category values(174, '광주남구재직자기타');
insert into category values(175, '광주남구창업자전체');
insert into category values(176, '광주남구창업자교육');
insert into category values(177, '광주남구창업자창업');
insert into category values(178, '광주남구창업자주거');
insert into category values(179, '광주남구창업자건강');
insert into category values(180, '광주남구창업자기타');
insert into category values(181, '광주남구장애인전체');
insert into category values(182, '광주남구장애인교육');
insert into category values(183, '광주남구장애인창업');
insert into category values(184, '광주남구장애인주거');
insert into category values(185, '광주남구장애인건강');
insert into category values(186, '광주남구장애인기타');
insert into category values(187, '광주남구임신부전체');
insert into category values(188, '광주남구임신부교육');
insert into category values(189, '광주남구임신부창업');
insert into category values(190, '광주남구임신부주거');
insert into category values(191, '광주남구임신부건강');
insert into category values(192, '광주남구임신부기타');
insert into category values(193, '광주동구전체전체');
insert into category values(194, '광주동구전체교육');
insert into category values(195, '광주동구전체창업');
insert into category values(196, '광주동구전체주거');
insert into category values(197, '광주동구전체건강');
insert into category values(198, '광주동구전체기타');
insert into category values(199, '광주동구대학생전체');
insert into category values(200, '광주동구대학생교육');
insert into category values(201,'광주동구대학생창업');
insert into category values(202,'광주동구대학생주거');
insert into category values(203,'광주동구대학생건강');
insert into category values(204,'광주동구대학생기타');
insert into category values(205,'광주동구군인전체');
insert into category values(206,'광주동구군인교육');
insert into category values(207,'광주동구군인창업');
insert into category values(208,'광주동구군인주거');
insert into category values(209,'광주동구군인건강');
insert into category values(210,'광주동구군인기타');
insert into category values(211,'광주동구구직전체');
insert into category values(212,'광주동구구직교육');
insert into category values(213,'광주동구구직창업');
insert into category values(214,'광주동구구직주거');
insert into category values(215,'광주동구구직건강');
insert into category values(216,'광주동구구직기타');
insert into category values(217,'광주동구재직자전체');
insert into category values(218,'광주동구재직자교육');
insert into category values(219,'광주동구재직자창업');
insert into category values(220,'광주동구재직자주거');
insert into category values(221,'광주동구재직자건강');
insert into category values(222,'광주동구재직자기타');
insert into category values(223,'광주동구창업자전체');
insert into category values(224,'광주동구창업자교육');
insert into category values(225,'광주동구창업자창업');
insert into category values(226,'광주동구창업자주거');
insert into category values(227,'광주동구창업자건강');
insert into category values(228,'광주동구창업자기타');
insert into category values(229,'광주동구장애인전체');
insert into category values(230,'광주동구장애인교육');
insert into category values(231,'광주동구장애인창업');
insert into category values(232,'광주동구장애인주거');
insert into category values(233,'광주동구장애인건강');
insert into category values(234,'광주동구장애인기타');
insert into category values(235,'광주동구임신부전체');
insert into category values(236,'광주동구임신부교육');
insert into category values(237,'광주동구임신부창업');
insert into category values(238,'광주동구임신부주거');
insert into category values(239,'광주동구임신부건강');
insert into category values(240,'광주동구임신부기타');
insert into category values(241,'광주서구전체전체');
insert into category values(242,'광주서구전체교육');
insert into category values(243,'광주서구전체창업');
insert into category values(244,'광주서구전체주거');
insert into category values(245,'광주서구전체건강');
insert into category values(246,'광주서구전체기타');
insert into category values(247,'광주서구대학생전체');
insert into category values(248,'광주서구대학생교육');
insert into category values(249,'광주서구대학생창업');
insert into category values(250,'광주서구대학생주거');
insert into category values(251,'광주서구대학생건강');
insert into category values(252,'광주서구대학생기타');
insert into category values(253,'광주서구군인전체');
insert into category values(254,'광주서구군인교육');
insert into category values(255,'광주서구군인창업');
insert into category values(256,'광주서구군인주거');
insert into category values(257,'광주서구군인건강');
insert into category values(258,'광주서구군인기타');
insert into category values(259,'광주서구구직전체');
insert into category values(260,'광주서구구직교육');
insert into category values(261,'광주서구구직창업');
insert into category values(262,'광주서구구직주거');
insert into category values(263,'광주서구구직건강');
insert into category values(264,'광주서구구직기타');
insert into category values(265,'광주서구재직자전체');
insert into category values(266,'광주서구재직자교육');
insert into category values(267,'광주서구재직자창업');
insert into category values(268,'광주서구재직자주거');
insert into category values(269,'광주서구재직자건강');
insert into category values(270,'광주서구재직자기타');
insert into category values(271,'광주서구창업자전체');
insert into category values(272,'광주서구창업자교육');
insert into category values(273,'광주서구창업자창업');
insert into category values(274,'광주서구창업자주거');
insert into category values(275,'광주서구창업자건강');
insert into category values(276,'광주서구창업자기타');
insert into category values(277,'광주서구장애인전체');
insert into category values(278,'광주서구장애인교육');
insert into category values(279,'광주서구장애인창업');
insert into category values(280,'광주서구장애인주거');
insert into category values(281,'광주서구장애인건강');
insert into category values(282,'광주서구장애인기타');
insert into category values(283,'광주서구임신부전체');
insert into category values(284,'광주서구임신부교육');
insert into category values(285,'광주서구임신부창업');
insert into category values(286,'광주서구임신부주거');
insert into category values(287,'광주서구임신부건강');
insert into category values(288,'광주서구임신부기타');
insert into category values(289,'광주광산구전체전체');
insert into category values(290,'광주광산구전체교육');
insert into category values(291,'광주광산구전체창업');
insert into category values(292,'광주광산구전체주거');
insert into category values(293,'광주광산구전체건강');
insert into category values(294,'광주광산구전체기타');
insert into category values(295,'광주광산구대학생전체');
insert into category values(296,'광주광산구대학생교육');
insert into category values(297,'광주광산구대학생창업');
insert into category values(298,'광주광산구대학생주거');
insert into category values(299,'광주광산구대학생건강');
insert into category values(300,'광주광산구대학생기타');
insert into category values(301,'광주광산구군인전체');
insert into category values(302,'광주광산구군인교육');
insert into category values(303,'광주광산구군인창업');
insert into category values(304,'광주광산구군인주거');
insert into category values(305,'광주광산구군인건강');
insert into category values(306,'광주광산구군인기타');
insert into category values(307,'광주광산구구직전체');
insert into category values(308,'광주광산구구직교육');
insert into category values(309,'광주광산구구직창업');
insert into category values(310,'광주광산구구직주거');
insert into category values(311,'광주광산구구직건강');
insert into category values(312,'광주광산구구직기타');
insert into category values(313,'광주광산구재직자전체');
insert into category values(314,'광주광산구재직자교육');
insert into category values(315,'광주광산구재직자창업');
insert into category values(316,'광주광산구재직자주거');
insert into category values(317,'광주광산구재직자건강');
insert into category values(318,'광주광산구재직자기타');
insert into category values(319,'광주광산구창업자전체');
insert into category values(320,'광주광산구창업자교육');
insert into category values(321,'광주광산구창업자창업');
insert into category values(322,'광주광산구창업자주거');
insert into category values(323,'광주광산구창업자건강');
insert into category values(324,'광주광산구창업자기타');
insert into category values(325,'광주광산구장애인전체');
insert into category values(326,'광주광산구장애인교육');
insert into category values(327,'광주광산구장애인창업');
insert into category values(328,'광주광산구장애인주거');
insert into category values(329,'광주광산구장애인건강');
insert into category values(330,'광주광산구장애인기타');
insert into category values(331,'광주광산구임신부전체');
insert into category values(332,'광주광산구임신부교육');
insert into category values(333,'광주광산구임신부창업');
insert into category values(334,'광주광산구임신부주거');
insert into category values(335,'광주광산구임신부건강');
insert into category values(336,'광주광산구임신부기타');